# Generated by Django 3.0.5 on 2022-09-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220922_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
